name: _
publish_to: none

repository: https://github.com/vowdemon/jolt

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/jolt
  - packages/jolt_flutter
  - packages/jolt_hooks
  - packages/jolt_surge
  - packages/jolt_setup
  - packages/jolt_devtools_extension
  - packages/jolt_hooks/example
  - packages/jolt_surge/example

dev_dependencies:
  melos: ^7.3.0

melos:
  categories:
    examples:
      - examples/*
    testable:
      - packages/jolt
      - packages/jolt_flutter
      - packages/jolt_hooks
      - packages/jolt_surge
      - packages/jolt_setup
  ide:
    intellij:
      enabled: false
  command:
    bootstrap:
      dependencies:
        meta: ^1.0.0

    version:
      branch: main
      releaseUrl: true
      includeCommitId: true
      linkToCommits: true

  scripts:
    test:
      run: |
        mkdir -p coverage
        flutter test \
          --coverage \
          --coverage-path=coverage/lcov.info \
          $(melos list --category=testable --parsable | sed 's#$#/test#')
      description: Run Flutter tests with coverage for melos testable packages.
    test:devtools:
      run: |
        cd packages/jolt_devtools_extension
        flutter test
      description: Run the jolt_devtools_extension package tests without coverage.
    test:lint:
      run: |
        cd packages/jolt_lint
        dart test
      description: Run the jolt_lint package tests without coverage.
    coverage:html:
      run: genhtml coverage/lcov.info -o coverage/html
      description: Generate HTML coverage report from workspace coverage output.
    analyze:
      run: melos exec -c 1 -- flutter analyze --no-fatal-infos --no-fatal-warnings
    update:version:
      run: melos version --no-published --no-private --no-git-commit-version
