name: Setup environment and cache dependencies
description: Prepare flutter and dart dependencies

runs:
  using: "composite"
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
    - name: Install melos
      run: dart pub global activate melos
      shell: bash
    - name: Run melos bootstrap
      run: melos bootstrap
      shell: bash
